version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: CP_CLP_DB_it
    environment:
      POSTGRES_DB: courtlistpublishing
      POSTGRES_USER: courtlistpublishing
      POSTGRES_PASSWORD: courtlistpublishing
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U courtlistpublishing -d courtlistpublishing" ]
      interval: 5s
      timeout: 3s
      retries: 30
  service-hmcts-marketplace-springboot-template:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        BASE_IMAGE: ${BASE_IMAGE}
        SERVER_PORT: ${SERVER_PORT}
        JAR_FILENAME: ${JAR_FILENAME}
        JAR_FILE_PATH: ${JAR_FILE_PATH}
    environment:
      - SERVER_PORT=${SERVER_PORT:-8082}
      - CP_CLP_DATASOURCE_URL=${CP_CLP_DATASOURCE_URL:-jdbc:postgresql://db:5432/courtlistpublishing}
      - CP_CLP_DATASOURCE_USERNAME=${CP_CLP_DATASOURCE_USERNAME:-app}
      - CP_CLP_DATASOURCE_PASSWORD=${CP_CLP_DATASOURCE_PASSWORD:-app}
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME:test-account-name}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID:test-client-id}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID:test-tenant-id}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${SERVER_PORT:-8082}:${SERVER_PORT:-8082}"
    networks:
      - service-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/courtlistpublishing-service/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  service-network:
    name: service-hmcts-marketplace-springboot-template-network
